### ISSUE TITLE
support add_argument like python

### ISSUE THREAD

**Issue by seqyuan** [clagraff/argparse#46]
Is there a way like this?

```python
def project_stat(args):
    pass

def delete_one_project_from_databse(args):
    pass

def main():
    parser=argparse.ArgumentParser(description='',
        formatter_class=argparse.RawDescriptionHelpFormatter)
    subparsers = parser.add_subparsers(dest='subparser_name',help='')

    stat_parser = subparsers.add_parser('stat', help='show flow line projects stat')
    stat_parser.add_argument('-p', dest='sub_project_id',default='', help='sub_project_id')
    stat_parser.set_defaults(func=project_stat)

    delete_parser = subparsers.add_parser('delid', help='delet one filter and analysisproject from database')
    delete_parser.add_argument('-spi', dest='sub_project_id',required=True, help='sub_project_id')
    delete_parser.set_defaults(func=delete_one_project_from_databse)
```

**Comment by clagraff** [comment]
That's an interesting suggestion.

Unfortunately, this project isn't really maintained anymore. It's kept around in case anyone had been using it previously, but otherwise im not making updates to it right now.

As such, I would encourage you to take a look at [some alternatives](https://github.com/avelino/awesome-go#command-line) that may best fit your needs.

My personal favorite is [kingpin](https://github.com/alecthomas/kingpin). Or if you want something still similar to python's `argparse` you could look at [akamensky's argparse](https://github.com/akamensky/argparse)
